server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show-sql: true
      format_sql: true

  kafka:
    consumer:
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9093,Kafka02Service:9094
    producer:
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9093,Kafka02Service:9094
