rabbitmq:
  queues:
    - name: customer_queue
      exchange: customer_exchange
      routingKey: customer_routingKey
    - name: reservation_queue
      exchange: reservation_exchange
      routingKey: reservation_routingKey
